In [1]:
import numpy as np

# Reshaping numpy arrays

In [2]:
a = np.array(range(10), float)

In [3]:
a

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

In [4]:
a = a.reshape(5,2)

In [5]:
a

array([[ 0.,  1.],
       [ 2.,  3.],
       [ 4.,  5.],
       [ 6.,  7.],
       [ 8.,  9.]])

# Creating lists from arrays

In [6]:
a = np.array([1,2,3], float)

In [7]:
a.tolist()

[1.0, 2.0, 3.0]

In [8]:
list(a)

[1.0, 2.0, 3.0]

# Converting to/from strings

In [9]:
a = np.array([1,2,3], float)

In [10]:
s = a.tostring()

In [11]:
s

'\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\x00@\x00\x00\x00\x00\x00\x00\x08@'

In [12]:
np.fromstring(s)

array([ 1.,  2.,  3.])

In [13]:
a

array([ 1.,  2.,  3.])

# Transposing arrays

In [14]:
a = np.array(range(6), float).reshape((2,3))

In [15]:
a

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.]])

In [16]:
a.transpose()

array([[ 0.,  3.],
       [ 1.,  4.],
       [ 2.,  5.]])

# Flattening arrays

In [17]:
a = np.array([[1,2,3], [4,5,6]], float)

In [18]:
a.flatten()

array([ 1.,  2.,  3.,  4.,  5.,  6.])

# Concatenating arrays

In [19]:
a = np.array([1,2], float)

In [20]:
b = np.array([3,4], float)

In [21]:
np.concatenate((a,b))

array([ 1.,  2.,  3.,  4.])

# Concatenating multi-dim arrays

In [22]:
a = np.array([[1,2], [3,4]], float)

In [23]:
b = np.array([[5,6], [7,8]], float)

In [24]:
np.concatenate((a,b))

array([[ 1.,  2.],
       [ 3.,  4.],
       [ 5.,  6.],
       [ 7.,  8.]])

In [25]:
np.concatenate((a,b), axis=1)

array([[ 1.,  2.,  5.,  6.],
       [ 3.,  4.,  7.,  8.]])

In [26]:
a = np.array([1,2,3], float)

# Changing axis of array

In [27]:
a[:, np.newaxis]

array([[ 1.],
       [ 2.],
       [ 3.]])

# Other ways to create arrays

In [28]:
range(5)

[0, 1, 2, 3, 4]

In [29]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [30]:
np.arange(5, dtype=float)

array([ 0.,  1.,  2.,  3.,  4.])

In [31]:
np.ones((2,3), dtype=float)

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [32]:
np.zeros(7, dtype=float)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [33]:
a = np.array([[1,2,3], [4,5,6]], float)

In [34]:
np.zeros_like(a)

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [35]:
np.ones_like(a)

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [36]:
np.identity(4, dtype=float)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [37]:
np.eye(4, k=1, dtype=float)

array([[ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  0.]])

# Array mathematics

In [38]:
a = np.array([1,2,3], float)

In [39]:
b = np.array([5,2,6], float)

In [40]:
a + b

array([ 6.,  4.,  9.])

In [41]:
a * b #element-wise multiplication

array([  5.,   4.,  18.])

In [42]:
b**a

array([   5.,    4.,  216.])

# Common mathematical functions

In [43]:
a = np.array([1,4,9], float)

In [44]:
np.sqrt(a)

array([ 1.,  2.,  3.])

In [45]:
a = np.array([1.1, 1.5, 1.9], float)

In [46]:
np.floor(a)

array([ 1.,  1.,  1.])

In [47]:
np.ceil(a)

array([ 2.,  2.,  2.])

In [48]:
np.rint(a)

array([ 1.,  2.,  2.])

In [49]:
np.pi

3.141592653589793

In [50]:
np.e

2.718281828459045

# Array iteration

In [51]:
a = np.array([1,4,5], int)

In [52]:
for x in a:
    print x

1
4
5


In [53]:
a = np.array([[1,2], [3,4], [5,6]], float)

In [54]:
a

array([[ 1.,  2.],
       [ 3.,  4.],
       [ 5.,  6.]])

In [55]:
for (x,y) in a:
    print x*y

2.0
12.0
30.0


# Basic array operations

In [56]:
a = np.array([2,4,3], float)

In [57]:
a.sum()

9.0

In [58]:
a.mean()

3.0

In [59]:
a.max()

4.0

In [60]:
a.min()

2.0

In [61]:
a.prod()

24.0

In [62]:
np.sum(a)

9.0

In [63]:
np.var(a)

0.66666666666666663

In [64]:
np.std(a)

0.81649658092772603

In [65]:
a.argmin()

0

In [66]:
a.argmax()

1

In [67]:
a = np.array([[0,2], [3,-1], [3,5]], float)

In [68]:
a

array([[ 0.,  2.],
       [ 3., -1.],
       [ 3.,  5.]])

In [69]:
a.mean(axis = 0)

array([ 2.,  2.])

In [70]:
a.mean(axis = 1)

array([ 1.,  1.,  4.])

In [71]:
a = np.array([6,2,5,-1,0], float)

In [72]:
sorted(a)

[-1.0, 0.0, 2.0, 5.0, 6.0]

In [73]:
a.sort()

In [74]:
a

array([-1.,  0.,  2.,  5.,  6.])

In [75]:
a = np.array([6,2,5,-1,0], float)

In [76]:
a.clip(0,5)

array([ 5.,  2.,  5.,  0.,  0.])

In [77]:
a = np.array([1,1,4,5,5,5,7], float)

In [78]:
np.unique(a)

array([ 1.,  4.,  5.,  7.])

In [79]:
a = np.array([[1,2], [3,4]], float)

In [80]:
a.diagonal()

array([ 1.,  4.])

# Comparison operators and value testing

In [81]:
a = np.array([1,3,0], float)

In [82]:
b = np.array([0,3,2], float)

In [83]:
a > b

array([ True, False, False], dtype=bool)

In [84]:
a > 2

array([False,  True, False], dtype=bool)

In [91]:
a = np.array([1,3,0], float)

In [92]:
a

array([ 1.,  3.,  0.])

In [97]:
np.where(a != 0, 1/a, a)

C:\Python27\lib\site-packages\ipykernel\__main__.py:1: RuntimeWarning: divide by zero encountered in divide
  if __name__ == '__main__':


array([ 1.        ,  0.33333333,  0.        ])

In [98]:
np.where(a > 0, 3,2)

array([3, 3, 2])

In [99]:
a.nonzero()

(array([0, 1], dtype=int64),)

In [100]:
a = np.array([[0,1],[3,4]], float)

In [101]:
a.nonzero()

(array([0, 1, 1], dtype=int64), array([1, 0, 1], dtype=int64))

In [102]:
np.isnan(a)

array([[False, False],
       [False, False]], dtype=bool)

In [103]:
a = np.array([1, np.NaN, np.Inf], float)

In [104]:
a

array([  1.,  nan,  inf])

In [105]:
np.isnan(a)

array([False,  True, False], dtype=bool)

In [106]:
np.isfinite(a)

array([ True, False, False], dtype=bool)

# Array item selection and manipulation

In [107]:
a = np.array([[6,4], [5,9]], float)

In [108]:
a >= 6

array([[ True, False],
       [False,  True]], dtype=bool)

In [109]:
a[a >= 6]

array([ 6.,  9.])

In [110]:
a[np.logical_and(a > 5, a < 9)]

array([ 6.])

In [111]:
a = np.array([[1,4],[9,16]], float)

In [112]:
b = np.array([0,0,1,1,0], int)

In [113]:
c = np.array([0, 1,1,1,1], int)

In [114]:
a[b,c]

array([  1.,   4.,  16.,  16.,   4.])

In [115]:
a[b]

array([[  1.,   4.],
       [  1.,   4.],
       [  9.,  16.],
       [  9.,  16.],
       [  1.,   4.]])

In [116]:
a.take(b)

array([ 1.,  1.,  4.,  4.,  1.])

## Vector and matrix mathematics

In [117]:
a = np.array([1,2,3], float)

In [118]:
b = np.array([0,1,1], float)

In [119]:
np.dot(a,b)

5.0

In [120]:
a = np.array([[0,1], [2,3]], float)

In [121]:
a

array([[ 0.,  1.],
       [ 2.,  3.]])

In [122]:
b = np.array([2,3], float)

In [123]:
b

array([ 2.,  3.])

In [124]:
c = np.array([[1,1], [4,0]], float)

In [125]:
c

array([[ 1.,  1.],
       [ 4.,  0.]])

In [126]:
np.dot(b,a)

array([  6.,  11.])

In [127]:
np.dot(a,b)

array([  3.,  13.])

In [128]:
np.dot(a,c) # matrix multiplication (A X C)

array([[  4.,   0.],
       [ 14.,   2.]])

In [129]:
a = np.array([1,4,0], float)

In [130]:
b = np.array([2,2,1], float)

In [131]:
np.outer(a,b)

array([[ 2.,  2.,  1.],
       [ 8.,  8.,  4.],
       [ 0.,  0.,  0.]])

In [132]:
np.inner(a,b)

10.0

In [133]:
np.cross(a,b) # ???????

array([ 4., -1., -6.])

In [134]:
a = np.array([[4,2,0], [9,3,7], [1,2,1]], float)

In [137]:
np.linalg.det(a)

-48.000000000000028

In [136]:
a

array([[ 4.,  2.,  0.],
       [ 9.,  3.,  7.],
       [ 1.,  2.,  1.]])

In [138]:
vals, vecs = np.linalg.eig(a)

In [139]:
vals

array([ 8.85591316,  1.9391628 , -2.79507597])

In [140]:
vecs

array([[-0.3663565 , -0.54736745,  0.25928158],
       [-0.88949768,  0.5640176 , -0.88091903],
       [-0.27308752,  0.61828231,  0.39592263]])

In [141]:
b = np.linalg.inv(a)

In [142]:
b

array([[ 0.22916667,  0.04166667, -0.29166667],
       [ 0.04166667, -0.08333333,  0.58333333],
       [-0.3125    ,  0.125     ,  0.125     ]])

In [143]:
np.dot(a,b) # should be identity

array([[  1.00000000e+00,   0.00000000e+00,  -2.22044605e-16],
       [  0.00000000e+00,   1.00000000e+00,   0.00000000e+00],
       [  0.00000000e+00,   0.00000000e+00,   1.00000000e+00]])

In [144]:
np.dot(b,a) # should be identity

array([[  1.00000000e+00,  -1.11022302e-16,  -5.55111512e-17],
       [  0.00000000e+00,   1.00000000e+00,   0.00000000e+00],
       [  2.77555756e-17,   5.55111512e-17,   1.00000000e+00]])

In [145]:
# Singular Value Decomposition (analogous to diagonalization of a nonsquare matrix)

In [146]:
a = np.array([[1,3,4], [5,2,3]], float)

In [147]:
a

array([[ 1.,  3.,  4.],
       [ 5.,  2.,  3.]])

In [148]:
U, s, Vh = np.linalg.svd(a)

In [149]:
U

array([[-0.6113829 , -0.79133492],
       [-0.79133492,  0.6113829 ]])

In [150]:
s

array([ 7.46791327,  2.86884495])

In [151]:
Vh

array([[-0.61169129, -0.45753324, -0.64536587],
       [ 0.78971838, -0.40129005, -0.46401635],
       [-0.046676  , -0.79349205,  0.60678804]])

# Polynomial mathematics

In [153]:
np.poly([-1, 1, 1, 10]) # for roots -1,1,1,10, polynomial is x^4 - 11x^3 + ...

array([  1, -11,   9,  11, -10])

In [154]:
np.roots([1, 4, -2, 3])

array([-4.57974010+0.j        ,  0.28987005+0.75566815j,
        0.28987005-0.75566815j])

In [155]:
np.roots([1, -11, 9, 11, -10])

array([ 10. +0.00000000e+00j,  -1. +0.00000000e+00j,   1. +9.63574370e-09j,
         1. -9.63574370e-09j])

In [156]:
np.polyint([1,1,1,1]) # integrating a polynomial

array([ 0.25      ,  0.33333333,  0.5       ,  1.        ,  0.        ])

In [158]:
np.polyder([1./4., 1./3., 1./2., 1., 0.]) # derivatives of a polynomial

array([ 1.,  1.,  1.,  1.])

In [159]:
np.polyval([1, -2, 0, 2], 4)

34

In [160]:
x = [1,2,3,4,5,6,7,8]

In [161]:
y = [0,2,1,3,7,10,11,19]

In [162]:
np.polyfit(x,y,2)

array([ 0.375     , -0.88690476,  1.05357143])

# Statistics

In [163]:
a = np.array(range(10), float)

In [164]:
a

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

In [165]:
np.median(a)

4.5

In [166]:
np.mean(a)

4.5

In [167]:
a.mean()

4.5

In [170]:
np.var(a)

8.25

In [171]:
np.std(a)

2.8722813232690143