In [1]:
import numpy as np

# Reshaping numpy arrays

In [2]:
a = np.array(range(10), float)

In [3]:
a

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

In [5]:
a = a.reshape(5,2)

In [6]:
a

array([[ 0.,  1.],
       [ 2.,  3.],
       [ 4.,  5.],
       [ 6.,  7.],
       [ 8.,  9.]])

# Creating lists from arrays

In [8]:
a = np.array([1,2,3], float)

In [9]:
a.tolist()

[1.0, 2.0, 3.0]

In [10]:
list(a)

[1.0, 2.0, 3.0]

# Converting to/from strings

In [11]:
a = np.array([1,2,3], float)

In [12]:
s = a.tostring()

In [13]:
s

'\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\x00@\x00\x00\x00\x00\x00\x00\x08@'

In [14]:
np.fromstring(s)

array([ 1.,  2.,  3.])

In [15]:
a

array([ 1.,  2.,  3.])

# Transposing arrays

In [20]:
a = np.array(range(6), float).reshape((2,3))

In [21]:
a

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.]])

In [23]:
a.transpose()

array([[ 0.,  3.],
       [ 1.,  4.],
       [ 2.,  5.]])

# Flattening arrays

In [24]:
a = np.array([[1,2,3], [4,5,6]], float)

In [25]:
a.flatten()

array([ 1.,  2.,  3.,  4.,  5.,  6.])

# Concatenating arrays

In [26]:
a = np.array([1,2], float)

In [27]:
b = np.array([3,4], float)

In [30]:
np.concatenate((a,b))

array([ 1.,  2.,  3.,  4.])

# Concatenating multi-dim arrays

In [31]:
a = np.array([[1,2], [3,4]], float)

In [32]:
b = np.array([[5,6], [7,8]], float)

In [33]:
np.concatenate((a,b))

array([[ 1.,  2.],
       [ 3.,  4.],
       [ 5.,  6.],
       [ 7.,  8.]])

In [34]:
np.concatenate((a,b), axis=1)

array([[ 1.,  2.,  5.,  6.],
       [ 3.,  4.,  7.,  8.]])

In [35]:
a = np.array([1,2,3], float)

# Changing axis of array

In [38]:
a[:, np.newaxis]

array([[ 1.],
       [ 2.],
       [ 3.]])

# Other ways to create arrays

In [39]:
range(5)

[0, 1, 2, 3, 4]

In [41]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [42]:
np.arange(5, dtype=float)

array([ 0.,  1.,  2.,  3.,  4.])

In [43]:
np.ones((2,3), dtype=float)

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [44]:
np.zeros(7, dtype=float)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [45]:
a = np.array([[1,2,3], [4,5,6]], float)

In [46]:
np.zeros_like(a)

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [47]:
np.ones_like(a)

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [48]:
np.identity(4, dtype=float)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [49]:
np.eye(4, k=1, dtype=float)

array([[ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  0.]])

# Array mathematics

In [50]:
a = np.array([1,2,3], float)

In [51]:
b = np.array([5,2,6], float)

In [52]:
a + b

array([ 6.,  4.,  9.])

In [55]:
a * b #element-wise multiplication

array([  5.,   4.,  18.])

In [54]:
b**a

array([   5.,    4.,  216.])

# Common mathematical functions

In [56]:
a = np.array([1,4,9], float)

In [57]:
np.sqrt(a)

array([ 1.,  2.,  3.])

In [58]:
a = np.array([1.1, 1.5, 1.9], float)

In [59]:
np.floor(a)

array([ 1.,  1.,  1.])

In [60]:
np.ceil(a)

array([ 2.,  2.,  2.])

In [61]:
np.rint(a)

array([ 1.,  2.,  2.])

In [62]:
np.pi

3.141592653589793

In [63]:
np.e

2.718281828459045

# Array iteration

In [64]:
a = np.array([1,4,5], int)

In [65]:
for x in a:
    print x

1
4
5


In [66]:
a = np.array([[1,2], [3,4], [5,6]], float)

In [67]:
a

array([[ 1.,  2.],
       [ 3.,  4.],
       [ 5.,  6.]])

In [68]:
for (x,y) in a:
    print x*y

2.0
12.0
30.0


# Basic array operations

In [69]:
a = np.array([2,4,3], float)

In [70]:
a.sum()

9.0

In [71]:
a.mean()

3.0

In [72]:
a.max()

4.0

In [73]:
a.min()

2.0

In [74]:
a.prod()

24.0

In [75]:
np.sum(a)

9.0

In [76]:
np.var(a)

0.66666666666666663

In [78]:
np.std(a)

0.81649658092772603

In [79]:
a.argmin()

0

In [80]:
a.argmax()

1

In [81]:
a = np.array([[0,2], [3,-1], [3,5]], float)

In [82]:
a

array([[ 0.,  2.],
       [ 3., -1.],
       [ 3.,  5.]])

In [83]:
a.mean(axis = 0)

array([ 2.,  2.])

In [84]:
a.mean(axis = 1)

array([ 1.,  1.,  4.])

In [85]:
a = np.array([6,2,5,-1,0], float)

In [86]:
sorted(a)

[-1.0, 0.0, 2.0, 5.0, 6.0]

In [87]:
a.sort()

In [88]:
a

array([-1.,  0.,  2.,  5.,  6.])

In [89]:
a = np.array([6,2,5,-1,0], float)

In [90]:
a.clip(0,5)

array([ 5.,  2.,  5.,  0.,  0.])

In [91]:
a = np.array([1,1,4,5,5,5,7], float)

In [93]:
np.unique(a)

array([ 1.,  4.,  5.,  7.])

In [94]:
a = np.array([[1,2], [3,4]], float)

In [95]:
a.diagonal()

array([ 1.,  4.])

# Comparison operators and value testing

In [96]:
a = np.array([1,3,0], float)

In [97]:
b = np.array([0,3,2], float)

In [98]:
a > b

array([ True, False, False], dtype=bool)

In [99]:
a > 2

array([False,  True, False], dtype=bool)